# YOLOv8n Model Development

Start by installing ultralytics, and then importing the first model

In [ ]:
"""
Installs Ultralytics

"""
# INSTALL ULTRALYTICS IN THE NEW CUDA ENVIRONMENT
%pip install ultralytics

Requirement already satisfied: ultralytics in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (8.4.185)
Requirement already satisfied: numpy>=1.23.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (2.5.2)
Requirement already satisfied: matplotlib>=3.3.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (3.11.2)
Requirement already satisfied: opencv-python!=4.13.0.90,>=4.7.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (5.0.0.93)
Requirement already satisfied: pillow>=7.1.2 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (12.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (2.34.2)
Requirement already satisfied: torch>=1.8.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (2.5.1+cu121)
Requirement already satisfied: torchvision>=0.9.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (0.20.1+cu121)
Requirement already satisfied: psutil>=5.8.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (7.2.2)
Requirement already satisfied: polars>=0.20.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (2.0.0)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (13.615.71)
Requirement already satisfied: ultralytics-thop>=2.2.3 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (2.2.3)
Requirement already satisfied: ultralytics-platform>=0.1.45 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics) (0.1.94)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (26.3)
Requirement already satisfied: pyparsing>=3 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.0.0)
Requirement already satisfied: polars-runtime-32==2.0.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from polars>=0.20.0->ultralytics) (2.0.0)
Requirement already satisfied: six>=1.6 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: tzdata in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (2026.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from requests>=2.23.0->ultralytics) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from requests>=2.23.0->ultralytics) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from requests>=2.23.0->ultralytics) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from requests>=2.23.0->ultralytics) (2026.10.23)
Requirement already satisfied: filelock in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (3.32.3)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (4.16.0)
Requirement already satisfied: networkx in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (2026.7.0)
Requirement already satisfied: setuptools in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (84.0.0)
Requirement already satisfied: sympy==1.13.1 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: httpx<1,>=0.28 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from ultralytics-platform>=0.1.45->ultralytics) (0.28.1)
Requirement already satisfied: anyio in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.45->ultralytics) (4.15.1)
Requirement already satisfied: httpcore==1.* in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.45->ultralytics) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.28->ultralytics-platform>=0.1.45->ultralytics) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\sadul\anaconda3\envs\mma3001\Lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

# Training test
Using one epoch to make sure everything is working before doing the actual fine tuning.

In [ ]:
"""
YOLOv8n One-epoch training test

"""

#Import YOLOv8
from ultralytics import YOLO
import torch

# Verify that GPU acceleration is available
print("CUDA available:", torch.cuda.is_available())
print("Training GPU:", torch.cuda.get_device_name(0))

# Path to the dataset configuration file.
# The YAML file contains the locations of the training,
# validation and test sets and the five defect classes.
dataset_yaml = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml"

# Load the pretrained YOLOv8n model.
# The pretrained weights provide the starting point
model = YOLO("yolov8n.pt")

# Perform one epoch only.
test_results = model.train(
    data=dataset_yaml,         # Dataset configuration
    epochs=1,                  # Single test epoch
    imgsz=640,                 # Training image resolution
    batch=8,                   # Images processed together
    device=0,                  # NVIDIA GPU 0
    workers=0,                 # Safer setting for Windows/Jupyter
    name="yolov8n_smoke_test", # Name of this test experiment
    seed=42,                   # Reproducibility
    deterministic=True,        # Improve reproducibility
    verbose=True               # Display training information
)

print("One-epoch training test completed.")

CUDA available: True
Training GPU: NVIDIA GeForce RTX 4060 Laptop GPU
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=1, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8n_smoke_test, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None

Matplotlib is building the font cache; this may take a moment.

Downloading https://ultralytics.com/assets/Arial.ttf to 'C:\Users\sadul\AppData\Roaming\Ultralytics\Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 6.5MB/s 0.1s 0.1s<0.0s
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752287  ultralytics.nn.modules.head.Detect           [5, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,011,823 parameters, 3,011,807 gradients, 8.2 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights\yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 6.5MB/s 0.8s.7s<0.1s0.8s
AMP: checks passed
WARNING train: Slow image access detected (ping: 0.4±0.2 ms, read: 8.2±0.7 MB/s, size: 65.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
train: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\train\labels... 3349 images, 684 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3349/3349 156.4it/s 21.4s0.0ss
train: New cache created: C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\train\labels.cache
WARNING val: Slow image access detected (ping: 0.6±0.2 ms, read: 6.0±0.8 MB/s, size: 66.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\valid\labels... 120 images, 14 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 120/120 139.6it/s 0.9s0.1s
val: New cache created: C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\valid\labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test\labels.jpg...
Using 3349 train, 120 val images for fraction=1.0 at imgsz=640
Using 0 dataloader workers
Logging results to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test
Starting training for 1 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      1.12G       2.33      13.99      2.116          5        640: 100% ━━━━━━━━━━━━ 419/419 2.8it/s 2:290.6sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.3it/s 6.0s0.7ss
                   all        120        121      0.161      0.103      0.116     0.0493

1 epochs completed in 0.045 hours.
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test\weights\last.pt, 6.5MB
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test\weights\best.pt, 6.5MB

Validating C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test\weights\best.pt...
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Model summary (fused): 73 layers, 3,133,679 parameters, 0 gradients, 8.6 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.9it/s 4.3s0.4ss
                   all        120        121      0.161      0.102      0.116     0.0492
            loose-meat          3          3          0          0          0          0
       packaging-error         23         34     0.0715     0.0612     0.0223     0.0058
          twisted-meat          3          3          0          0          0          0
              unsealed         81         81      0.571      0.346      0.442      0.191
Speed: 0.7ms preprocess, 4.7ms inference, 0.0ms loss, 3.3ms postprocess per image
Results saved to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_smoke_test
One-epoch training test completed.

This confirms that the YOLOv8n model is working as intended and is ready for the actual run.

# Completing a full YOLOv8n Training run
Fine-tuning the model for 30 epochs. The model performance is being monitored by using recall, mAP@0.5, and mAP@0.5:0.95

In [ ]:
"""
Full YOLOv8n training using 30 epoch
"""
# Full YOLOv8n training
from ultralytics import YOLO
import torch

# Dataset configuration file
dataset_yaml = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml"

# Verify that GPU acceleration is available
print("CUDA available:", torch.cuda.is_available())
print("Training GPU:", torch.cuda.get_device_name(0))

# Reload the original pretrained model.
model = YOLO("yolov8n.pt")

# Train the first comparison model
yolov8n_results = model.train(
    data=dataset_yaml,             # Dataset paths and class names
    epochs=30,                     # Maximum training epochs
    patience=8,                    # Stop early if validation stops improving
    imgsz=640,                     # Input resolution
    batch=8,                       # Batch size suitable for initial testing
    device=0,                      # RTX 4060 GPU
    workers=0,                     # Stable setting for Windows notebooks
    name="yolov8n_full_training",  # Output directory name
    seed=42,                       # Reproducibility
    deterministic=True,            # More consistent repeated experiments
    plots=True,                    # Generate training and validation figures
    verbose=True                   # Display progress
)

print("Full YOLOv8n training completed.")

CUDA available: True
Training GPU: NVIDIA GeForce RTX 4060 Laptop GPU
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8n_full_training, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=8, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_full_training, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752287  ultralytics.nn.modules.head.Detect           [5, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,011,823 parameters, 3,011,807 gradients, 8.2 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
WARNING train: Slow image access detected (ping: 0.1±0.0 ms, read: 10.9±1.6 MB/s, size: 65.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
train: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\train\labels.cache... 3349 images, 684 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3349/3349  0.0s
WARNING val: Slow image access detected (ping: 0.1±0.0 ms, read: 10.9±1.4 MB/s, size: 66.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\valid\labels.cache... 120 images, 14 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 120/120  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_full_training\labels.jpg...
Using 3349 train, 120 val images for fraction=1.0 at imgsz=640
Using 0 dataloader workers
Logging results to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_full_training
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      1.17G      1.914      4.518      1.703          5        640: 100% ━━━━━━━━━━━━ 419/419 2.0it/s 3:300.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.6it/s 2.2s0.3s
                   all        120        121      0.717      0.245      0.251      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      1.27G      1.876      1.952      1.559          8        640: 100% ━━━━━━━━━━━━ 419/419 1.9it/s 3:410.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.6it/s 1.4s0.2s
                   all        120        121      0.776      0.226      0.242       0.13

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      1.27G      1.845       1.73       1.53          9        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:340.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121       0.72      0.273      0.242      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      1.27G      1.795      1.628      1.495          7        640: 100% ━━━━━━━━━━━━ 419/419 3.2it/s 2:110.6sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 2.0it/s 4.0s0.6ss
                   all        120        121      0.763      0.239      0.265       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      1.27G      1.739      1.512      1.451          9        640: 100% ━━━━━━━━━━━━ 419/419 1.7it/s 4:100.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.4it/s 5.6s0.8ss
                   all        120        121      0.752      0.322      0.315      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      1.27G       1.72      1.448      1.433          9        640: 100% ━━━━━━━━━━━━ 419/419 1.8it/s 3:540.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.7it/s 2.1s0.3s
                   all        120        121      0.771      0.251      0.362      0.223

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      1.27G      1.662      1.394      1.397          7        640: 100% ━━━━━━━━━━━━ 419/419 1.9it/s 3:380.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.6it/s 2.2s0.3ss
                   all        120        121      0.759      0.262      0.309        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      1.27G      1.631       1.37      1.385          7        640: 100% ━━━━━━━━━━━━ 419/419 3.7it/s 1:540.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 4.3it/s 1.9s0.3s
                   all        120        121       0.83      0.297      0.357      0.197

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      1.27G       1.62      1.324      1.379         11        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:360.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.9it/s 1.4s0.2s
                   all        120        121       0.79      0.302      0.362      0.208

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      1.27G      1.582       1.31      1.348          8        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:360.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121      0.772      0.296      0.327        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      1.27G      1.592       1.29      1.366         10        640: 100% ━━━━━━━━━━━━ 419/419 4.6it/s 1:300.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.5it/s 1.2s0.2s
                   all        120        121      0.758      0.391      0.401      0.222

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      1.27G      1.525      1.208      1.333          8        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:370.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121      0.733      0.292      0.324      0.198

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      1.27G      1.528      1.184      1.332          8        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:360.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.2it/s 1.5s0.2s
                   all        120        121      0.363      0.538      0.459      0.274

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      1.27G      1.523      1.194      1.326          8        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:350.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121       0.45      0.497      0.487      0.271

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      1.27G      1.484      1.133       1.29         10        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:350.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.0it/s 1.3s0.2s
                   all        120        121       0.36      0.557      0.511      0.266

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      1.27G      1.448      1.098      1.285          3        640: 100% ━━━━━━━━━━━━ 419/419 4.6it/s 1:320.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121      0.658      0.469      0.492       0.29

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      1.27G       1.45      1.093      1.287          7        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:360.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121       0.28      0.538      0.471      0.299

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      1.27G      1.404      1.047      1.267         10        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:370.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.3it/s 1.3s0.2s
                   all        120        121      0.811      0.311      0.476      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30      1.27G      1.376      1.031      1.255          2        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:380.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121      0.818      0.417      0.496      0.326

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      1.27G      1.384      1.019      1.255         11        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:390.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.0it/s 1.3s0.2s
                   all        120        121      0.828      0.472       0.49      0.304
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      1.27G      1.416      1.002      1.292          5        640: 100% ━━━━━━━━━━━━ 419/419 5.7it/s 1:140.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.3it/s 1.3s0.2s
                   all        120        121      0.633      0.494      0.474      0.275

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      1.27G       1.37     0.9618      1.268          3        640: 100% ━━━━━━━━━━━━ 419/419 5.7it/s 1:130.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.6it/s 1.2s0.2s
                   all        120        121      0.551      0.499      0.516      0.297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      1.27G      1.349     0.9271      1.262          6        640: 100% ━━━━━━━━━━━━ 419/419 5.4it/s 1:170.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        120        121      0.561      0.546      0.525      0.309

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      1.27G      1.307     0.8854      1.249          4        640: 100% ━━━━━━━━━━━━ 419/419 5.7it/s 1:130.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.4it/s 1.2s0.2s
                   all        120        121      0.762      0.496       0.54      0.301

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30      1.27G      1.314     0.8796      1.237          4        640: 100% ━━━━━━━━━━━━ 419/419 4.7it/s 1:290.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.0it/s 1.6s0.2s
                   all        120        121      0.783       0.44      0.526      0.296

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30      1.27G       1.29     0.8661      1.234          4        640: 100% ━━━━━━━━━━━━ 419/419 4.7it/s 1:290.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.616       0.56      0.579      0.332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30      1.27G      1.245     0.8343       1.21          3        640: 100% ━━━━━━━━━━━━ 419/419 5.1it/s 1:220.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.4it/s 1.2s0.2s
                   all        120        121      0.406      0.595      0.541      0.296

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30      1.27G      1.216     0.8117      1.187          5        640: 100% ━━━━━━━━━━━━ 419/419 5.1it/s 1:220.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 10.2it/s 0.8s.1s
                   all        120        121      0.773      0.378      0.496      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30      1.27G      1.193     0.7918      1.183          4        640: 100% ━━━━━━━━━━━━ 419/419 5.7it/s 1:140.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121       0.77      0.386      0.475      0.282

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30      1.27G      1.191     0.7819      1.178          4        640: 100% ━━━━━━━━━━━━ 419/419 5.5it/s 1:160.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.4it/s 1.2s0.2s
                   all        120        121      0.401      0.474      0.499      0.288

30 epochs completed in 0.965 hours.
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_full_training\weights\last.pt, 6.5MB
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_full_training\weights\best.pt, 6.5MB

Validating C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8n_full_training\weights\best.pt...
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Model summary (fused): 73 layers, 3,133,679 parameters, 0 gradients, 8.6 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.3s0.3s
                   all        120        121      0.609       0.56      0.577      0.329
            loose-meat          3          3      0.887      0.333      0.408      0.145

# Evaluation YOLOv8n
Assessing the best performance of the model

In [ ]:
"""
Evaluate YOLOv8n on the held-out test set
"""
#Imports
from ultralytics import YOLO
import os

# Path to the dataset configuration file
dataset_yaml = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml"

# Path to the best model produced during the 30-epoch training run.
# best.pt represents the checkpoint with the best validation performance
best_model_path = os.path.join(
    "runs",
    "detect",
    "yolov8n_full_training",
    "weights",
    "best.pt"
)

# Load the best trained YOLOv8n checkpoint
best_model = YOLO(best_model_path)

# Evaluate the model using the held-out test dataset.
test_results = best_model.val(
    data=dataset_yaml,
    split="test",
    imgsz=640,
    batch=8,
    device=0,
    workers=0,
    plots=True
)

#Display all the best test results
print("\nYOLOv8n TEST RESULTS")
print("--------------------")

# Overall precision across defect classes
print(f"Precision:      {test_results.box.mp:.4f}")

# Overall recall across defect classes
print(f"Recall:         {test_results.box.mr:.4f}")

# Mean Average Precision using IoU = 0.50
print(f"mAP@0.5:        {test_results.box.map50:.4f}")

# Mean Average Precision averaged across IoU thresholds 0.50-0.95
print(f"mAP@0.5:0.95:   {test_results.box.map:.4f}")

Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Model summary (fused): 73 layers, 3,133,679 parameters, 0 gradients, 8.6 GFLOPs
WARNING val: Slow image access detected (ping: 0.1±0.0 ms, read: 10.4±0.2 MB/s, size: 65.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\test\labels.cache... 80 images, 12 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 80/80  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.0it/s 2.0s.2s
                   all         80         79      0.853      0.335      0.421      0.206
            loose-meat          2          3          1          0      0.271      0.113
       packaging-error         16         23      0.611      0.522      0.534      0.115
          twisted-meat          4          4          1          0     0.0188     0.0132
              unsealed         49         49      0.801      0.816      0.858      0.585
Speed: 0.4ms preprocess, 3.3ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\val-2

YOLOv8n TEST RESULTS
--------------------
Precision:      0.8529
Recall:         0.3345
mAP@0.5:        0.4206
mAP@0.5:0.95:   0.2063

This forms the basis of the comparison between the n and s YOLO models

Next find the performance per class of packaging defect.

In [ ]:
"""
YOLOv8n test performance per defect class
"""
#Imports
import pandas as pd

# Retrieve the per-class results from the test evaluation
class_results = test_results.summary()

# Convert results into a readable table
class_results_df = pd.DataFrame(class_results)
class_results_df

,Class,Images,Instances,Box-P,Box-R,Box-F1,mAP50,mAP75,mAP50-95
0,loose-meat,2,3,1.00000,0.00000,0.00000,0.27136,0.00000,0.11273
1,packaging-error,16,23,0.61053,0.52174,0.56265,0.53426,0.01268,0.11450
2,twisted-meat,4,4,1.00000,0.00000,0.00000,0.01885,0.01885,0.01319
3,unsealed,49,49,0.80088,0.81633,0.80853,0.85794,0.69370,0.58485

From this table it can be seen that there is no class for wrinkle. To check if this is an issue with the model developement or a limitation of the provided dataset, find the number of images per defect in the test set.

In [ ]:
"""
Count defect numbers in the test set
"""
#Import
import os
from collections import Counter

# Path to the complete dataset
dataset_path = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8"

# Path containing the ground-truth YOLO annotations for the held-out test dataset
test_labels_path = os.path.join(dataset_path, "test", "labels")

# Defect classes defined in data.yaml
class_names = {
    0: "loose-meat",
    1: "packaging-error",
    2: "twisted-meat",
    3: "unsealed",
    4: "wrinkle"
}

# Create a counter for each class
class_counts = Counter()

# Loop through every label file in the test dataset
for label_file in os.listdir(test_labels_path):

    # Only process YOLO .txt annotation files
    if label_file.endswith(".txt"):

        label_path = os.path.join(test_labels_path, label_file)

        # Read each ground-truth object annotation
        with open(label_path, "r") as file:

            for line in file:

                # Ignore empty annotation lines
                if not line.strip():
                    continue

                # YOLO format:
                # class_id x_center y_center width height
                values = line.strip().split()

                # Retrieve the defect class ID
                class_id = int(values[0])

                # Add one instance to that class
                class_counts[class_id] += 1

print("TEST SET GROUND-TRUTH CLASS DISTRIBUTION")
print("----------------------------------------")

total_instances = 0

# Loop through ALL five classes.
for class_id, class_name in class_names.items():

    count = class_counts[class_id]

    print(f"{class_name:<20}: {count}")

    total_instances += count

print("----------------------------------------")
print(f"Total defect instances: {total_instances}")

TEST SET GROUND-TRUTH CLASS DISTRIBUTION
----------------------------------------
loose-meat          : 3
packaging-error     : 23
twisted-meat        : 4
unsealed            : 49
wrinkle             : 0
----------------------------------------
Total defect instances: 79

This reveals that there is a new limitation, as there is 0 ground-truth data instances for the wrinkle defect class type.

# Defect Severity Analysis 
Using the new fine-tuned YOLOv8n model, we are completing an analysis on if it can identify the severity of the defect using the previously established values that can be accessed in the data exploration section of this project.

In [ ]:
"""
YOLOv8n defect-severity analysis
"""
#Imports
from ultralytics import YOLO
from pathlib import Path
import numpy as np
import pandas as pd

# Root folder of the downloaded Roboflow dataset
dataset_path = Path(
    r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8"
)

# Folder containing the 80 held-out test images
test_images_path = dataset_path / "test" / "images"

# Folder containing the corresponding ground-truth labels
test_labels_path = dataset_path / "test" / "labels"

# Path to the best YOLOv8n checkpoint
best_model_path = Path(
    "runs/detect/yolov8n_full_training/weights/best.pt"
)

# Confirm that all required paths are available
print("Test images found:", test_images_path.exists())
print("Test labels found:", test_labels_path.exists())
print("Best model found:", best_model_path.exists())


#Defect classes
class_names = {
    0: "loose-meat",
    1: "packaging-error",
    2: "twisted-meat",
    3: "unsealed",
    4: "wrinkle"
}


def classify_severity(relative_area):
    """
    Classify a defect according to its normalised bounding-box area.

    Parameters
    relative_area : float
        Bounding-box area expressed as a proportion of the complete image area.

    Returns
    str
        Low, Medium or High severity.
    """
#Using values calculated in 01 notebook
    if relative_area < 0.003254:
        return "Low"

    elif relative_area <= 0.089605:
        return "Medium"

    else:
        return "High"


def yolo_to_xyxy(x_center, y_center, width, height):
    """
    Convert a normalised YOLO bounding box from centre format to corner format.

    Parameter
        x_center, y_center, width, height

    Returns
        x_min, y_min, x_max, y_max

    """

    x_min = x_center - width / 2
    y_min = y_center - height / 2
    x_max = x_center + width / 2
    y_max = y_center + height / 2

    return np.array([x_min, y_min, x_max, y_max], dtype=float)


def calculate_iou(box_a, box_b):
    """
    Calculate Intersection over Union between two boxes.

    Parameters
    box_a : array-like
        First box in x_min, y_min, x_max, y_max format.

    box_b : array-like
        Second box in x_min, y_min, x_max, y_max format.

    Returns
    float
        IoU value between 0 and 1.
    """

    # Find the overlapping rectangle
    intersection_x_min = max(box_a[0], box_b[0])
    intersection_y_min = max(box_a[1], box_b[1])
    intersection_x_max = min(box_a[2], box_b[2])
    intersection_y_max = min(box_a[3], box_b[3])

    # Calculate overlap width and height
    intersection_width = max(
        0.0,
        intersection_x_max - intersection_x_min
    )

    intersection_height = max(
        0.0,
        intersection_y_max - intersection_y_min
    )

    # Calculate the intersection area
    intersection_area = (
        intersection_width * intersection_height
    )

    # Calculate individual box areas
    area_a = max(0.0, box_a[2] - box_a[0]) * max(
        0.0,
        box_a[3] - box_a[1]
    )

    area_b = max(0.0, box_b[2] - box_b[0]) * max(
        0.0,
        box_b[3] - box_b[1]
    )

    # Calculate the union area
    union_area = area_a + area_b - intersection_area

    # Prevent division by zero
    if union_area <= 0:
        return 0.0

    return intersection_area / union_area


def load_ground_truth(label_path):
    """
    Read one YOLO label file.

    Returns
    - class ID
    - normalised bounding box
    - normalised bounding-box area
    - severity classification
    """

    annotations = []

    # Some images may contain no labelled defects
    if not label_path.exists():
        return annotations

    with open(label_path, "r") as file:

        for line in file:

            # Ignore empty lines
            if not line.strip():
                continue

            values = line.strip().split()

            class_id = int(values[0])
            x_center = float(values[1])
            y_center = float(values[2])
            width = float(values[3])
            height = float(values[4])

            # Relative bounding-box area
            relative_area = width * height

            annotations.append(
                {
                    "class_id": class_id,
                    "box": yolo_to_xyxy(
                        x_center,
                        y_center,
                        width,
                        height
                    ),
                    "area": relative_area,
                    "severity": classify_severity(relative_area)
                }
            )

    return annotations

#Load the model
severity_model = YOLO(str(best_model_path))

prediction_results = severity_model.predict(
    source=str(test_images_path),
    imgsz=640,
    #Only accepting predictions with a 25% or higher confidence
    conf=0.25,
    device=0,

    save=False,
    stream=True,
    verbose=False
)

#Match predictions to the threshold
IOU_THRESHOLD = 0.50

matched_records = []
total_ground_truth = 0
total_predictions = 0
unmatched_ground_truth = 0
unmatched_predictions = 0


for result in prediction_results:

    # Locate the test image and its matching label file
    image_path = Path(result.path)
    label_path = test_labels_path / f"{image_path.stem}.txt"

    # Read ground-truth annotations
    ground_truth = load_ground_truth(label_path)

    # Store model predictions for the current image
    predictions = []

    if result.boxes is not None:

        # Predicted boxes are converted to normalised xyxy format
        predicted_boxes = result.boxes.xyxyn.cpu().numpy()
        predicted_classes = (
            result.boxes.cls.cpu().numpy().astype(int)
        )
        predicted_confidences = (
            result.boxes.conf.cpu().numpy()
        )

        for box, class_id, confidence in zip(
            predicted_boxes,
            predicted_classes,
            predicted_confidences
        ):

            # Calculate normalised prediction area
            predicted_width = max(0.0, box[2] - box[0])
            predicted_height = max(0.0, box[3] - box[1])
            predicted_area = predicted_width * predicted_height

            predictions.append(
                {
                    "class_id": class_id,
                    "box": box,
                    "area": predicted_area,
                    "severity": classify_severity(predicted_area),
                    "confidence": confidence
                }
            )

    total_ground_truth += len(ground_truth)
    total_predictions += len(predictions)

    # Keep track of predictions already assigned to ground truth
    used_prediction_indices = set()

    # Match each ground-truth defect to the unused same-class prediction with the highest IoU
    for gt in ground_truth:

        best_prediction_index = None
        best_iou = 0.0

        for prediction_index, prediction in enumerate(predictions):

            # Do not reuse a prediction
            if prediction_index in used_prediction_indices:
                continue

            # Only compare detections of the same defect class
            if prediction["class_id"] != gt["class_id"]:
                continue

            current_iou = calculate_iou(
                gt["box"],
                prediction["box"]
            )

            if current_iou > best_iou:
                best_iou = current_iou
                best_prediction_index = prediction_index

        # Accept the match when IoU is at least 0.50
        if (
            best_prediction_index is not None
            and best_iou >= IOU_THRESHOLD
        ):

            used_prediction_indices.add(best_prediction_index)

            matched_prediction = predictions[
                best_prediction_index
            ]

            matched_records.append(
                {
                    "image": image_path.name,
                    "class_id": gt["class_id"],
                    "class_name": class_names[gt["class_id"]],
                    "iou": best_iou,
                    "confidence": matched_prediction["confidence"],
                    "ground_truth_area": gt["area"],
                    "predicted_area": matched_prediction["area"],
                    "ground_truth_severity": gt["severity"],
                    "predicted_severity": matched_prediction["severity"],
                    "severity_correct": (
                        gt["severity"]
                        == matched_prediction["severity"]
                    )
                }
            )

        else:
            # Ground truth was missed or incorrectly classified
            unmatched_ground_truth += 1

    # Predictions that were not paired are false positives
    unmatched_predictions += (
        len(predictions) - len(used_prediction_indices)
    )

#Generate a results table
severity_results_df = pd.DataFrame(matched_records)

print("SEVERITY VALIDATION COMPLETE")
print("----------------------------")
print(f"Ground-truth defects:       {total_ground_truth}")
print(f"Model predictions:          {total_predictions}")
print(f"Matched defects:            {len(severity_results_df)}")
print(f"Unmatched ground truth:     {unmatched_ground_truth}")
print(f"Unmatched predictions:      {unmatched_predictions}")

if len(severity_results_df) > 0:

    # Percentage of matched detections with the correct severity
    severity_accuracy = (
        severity_results_df["severity_correct"].mean()
    )

    # Mean absolute error between predicted and true
    # normalised bounding-box areas
    area_mae = np.mean(
        np.abs(
            severity_results_df["predicted_area"]
            - severity_results_df["ground_truth_area"]
        )
    )

    # Percentage of all ground-truth defects that were matched
    matched_detection_rate = (
        len(severity_results_df) / total_ground_truth
    )

    print("\nSEVERITY RESULTS")
    print("----------------")
    print(
        f"Matched severity accuracy: "
        f"{severity_accuracy:.4f}"
    )

    print(
        f"Matched detection rate:     "
        f"{matched_detection_rate:.4f}"
    )

    print(
        f"Bounding-box area MAE:       "
        f"{area_mae:.6f}"
    )

else:
    print("No defects satisfied the matching criteria.")


# Display the first matched results
severity_results_df.head(10)

Test images found: True
Test labels found: True
Best model found: True
SEVERITY VALIDATION COMPLETE
----------------------------
Ground-truth defects:       79
Model predictions:          76
Matched defects:            56
Unmatched ground truth:     23
Unmatched predictions:      20

SEVERITY RESULTS
----------------
Matched severity accuracy: 0.9464
Matched detection rate:     0.7089
Bounding-box area MAE:       0.010867

,image,class_id,class_name,iou,confidence,ground_truth_area,predicted_area,ground_truth_severity,predicted_severity,severity_correct
0,frame_with_red_102_jpg.rf.10163b7e614de52a86d7...,3,unsealed,0.609492,0.834383,0.123912,0.202384,High,High,True
1,frame_with_red_1271_jpg.rf.fe7e60f579e43de1fb7...,3,unsealed,0.794876,0.848489,0.096543,0.096799,High,High,True
2,frame_with_red_1405_jpg.rf.061b0a529d86947d726...,3,unsealed,0.813323,0.809074,0.100823,0.099900,High,High,True
3,frame_with_red_1427_jpg.rf.adb68bb9baac518a460...,3,unsealed,0.774526,0.707997,0.088035,0.092321,Medium,High,False
4,frame_with_red_1458_jpg.rf.ae22a9f677e9aed6399...,1,packaging-error,0.673067,0.255302,0.078652,0.077419,Medium,Medium,True
5,frame_with_red_1521_jpg.rf.8c2f93027627984923b...,3,unsealed,0.883978,0.884112,0.131944,0.148637,High,High,True
6,frame_with_red_161_jpg.rf.f72001c0662bd4c49556...,3,unsealed,0.796469,0.357182,0.041968,0.050854,Medium,Medium,True
7,frame_with_red_1787_jpg.rf.2ea27acbeb8b9e0111c...,3,unsealed,0.903463,0.845650,0.121682,0.109935,High,High,True
8,frame_with_red_21_jpg.rf.898d2cd3db0cf96ae2985...,1,packaging-error,0.614931,0.553021,0.023868,0.014677,Medium,Medium,True
9,frame_with_red_2942_jpg.rf.f88a77f5e5850991ece...,3,unsealed,0.911482,0.725065,0.082685,0.089064,Medium,Medium,True

### YOLOv8n Severity Validation Results

The YOLOv8n model matched 56 of the 79 ground-truth defects using criteria. This produced a detection rate of 70.89%.

From the matched defects, the predicted severity category agreed with the ground-truth severity category in 94.64% of cases. This indicates that bounding-box area provided a consistent severity estimate when the model successfully detected and localised a defect.

However, 23 ground-truth defects were not matched. Defect detection and localisation remain more significant limitations than severity classification itself.

# Confusion matrix

In [ ]:
"""
Create a confusion matrix 
"""

#Order
severity_order = ["Low", "Medium", "High"]

# Compare ground-truth severity with predicted severity
severity_confusion_matrix = pd.crosstab(
    severity_results_df["ground_truth_severity"],
    severity_results_df["predicted_severity"],
    rownames=["Ground Truth"],
    colnames=["Predicted"],
    dropna=False
)

severity_confusion_matrix = severity_confusion_matrix.reindex(
    index=severity_order,
    columns=severity_order,
    fill_value=0
)

severity_confusion_matrix

Predicted     Low  Medium  High
Ground Truth
Low             0       0     0
Medium          0      24     2
High            0       1    29

Of the 56 correctly matched defects, 53 were assigned the correct severity category, corresponding to a matched severity accuracy of 94.64%.

For Medium-severity defects, 24 of 26 were correctly classified, while two were overestimated as High severity. For High-severity defects, 29 of 30 were correctly classified, while one was underestimated as Medium severity.

No low-severity defects were present among the successfully matched test detections.

These results indicate that bounding-box area provides a consistent severity estimate for successfully detected Medium and High-severity defects. However, overall system performance remains dependent on the object detector successfully identifying and localising the defect.