# YOLOv8s Model Development

Import the YOLOv8s model to this new file

In [ ]:
"""
Check if the YOLOv8s is able to load similar to the n model.
"""
#Imports
import torch
from ultralytics import YOLO

# Load pretrained YOLOv8s
model_s = YOLO("yolov8s.pt")

print("YOLOv8s loaded successfully.")

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8s.pt to 'yolov8s.pt': 100% ━━━━━━━━━━━━ 21.5MB 6.5MB/s 3.3s3.3s<0.0s3s
YOLOv8s loaded successfully.

# Training test
Using one epoch to make sure everything is working before doing the actual fine tuning. This uses the same values as the YOLOv8n model to ensure a fair comparison

In [ ]:
"""
YOLOv8s one epoch training test
"""

# Dataset configuration used for BOTH models
dataset_yaml = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml"

# Reload the original pretrained YOLOv8s model
model_s = YOLO("yolov8s.pt")

# Perform one test epoch
smoke_results_s = model_s.train(
    data=dataset_yaml,
    epochs=1,
    imgsz=640,
    batch=8,
    device=0,
    workers=0,
    name="yolov8s_smoke_test",
    seed=42,
    deterministic=True,
    verbose=True
)

print("YOLOv8s one-epoch test completed.")

Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=1, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8s_smoke_test, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117983  ultralytics.nn.modules.head.Detect           [5, 16, None, [128, 256, 512]]
Model summary: 129 layers, 11,137,535 parameters, 11,137,519 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
WARNING train: Slow image access detected (ping: 0.1±0.0 ms, read: 10.6±0.8 MB/s, size: 65.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
train: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\train\labels.cache... 3349 images, 684 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3349/3349  0.0s
WARNING val: Slow image access detected (ping: 0.1±0.0 ms, read: 10.9±0.3 MB/s, size: 66.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\valid\labels.cache... 120 images, 14 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 120/120  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test\labels.jpg...
Using 3349 train, 120 val images for fraction=1.0 at imgsz=640
Using 0 dataloader workers
Logging results to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test
Starting training for 1 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      1.97G      2.613      9.353      2.195          5        640: 100% ━━━━━━━━━━━━ 419/419 3.9it/s 1:480.3sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 2.6it/s 3.1s0.4s
                   all        120        121      0.373      0.165      0.146     0.0628

1 epochs completed in 0.032 hours.
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test\weights\last.pt, 22.5MB
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test\weights\best.pt, 22.5MB

Validating C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test\weights\best.pt...
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Model summary (fused): 72 layers, 11,127,519 parameters, 0 gradients, 28.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.3ss
                   all        120        121      0.372      0.165      0.146     0.0624
            loose-meat          3          3          0          0          0          0
       packaging-error         23         34     0.0425     0.0588     0.0349     0.0122
          twisted-meat          3          3          1          0     0.0606     0.0294
              unsealed         81         81      0.445      0.603      0.488      0.208
Speed: 0.4ms preprocess, 5.1ms inference, 0.0ms loss, 1.5ms postprocess per image
Results saved to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_smoke_test
YOLOv8s one-epoch test completed.

# Completing a full YOLOv8s Training run
Fine-tuning the model for 30 epochs. The model performance is being monitored by using recall, mAP@0.5, and mAP@0.5:0.95. The same parameters set for the YOLOv8n model to ensure a fair and easy comparison.

In [ ]:
"""
Full YOLOv8s training using 30 epoch
"""

#Imports
from ultralytics import YOLO
import torch

# Path to the same dataset configuration used for YOLOv8n
dataset_yaml = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml"

# Confirm GPU acceleration remains available.
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Training GPU:", torch.cuda.get_device_name(0))

# Load the ORIGINAL pretrained YOLOv8s model.
model_s = YOLO("yolov8s.pt")

# Train YOLOv8s using the same core experimental settings that were used for YOLOv8n.
yolov8s_results = model_s.train(

    # Dataset configuration
    data=dataset_yaml,

    # Maximum number of complete passes through the training set
    epochs=30,

    # Stop early if validation performance does not improve for eight consecutive epochs
    patience=8,

    # Input image resolution
    imgsz=640,

    # Number of images processed simultaneously
    batch=8,

    # Use the NVIDIA RTX 4060
    device=0,

    # Stable Windows/Jupyter data-loading configuration
    workers=0,

    # Separate output folder from YOLOv8n
    name="yolov8s_full_training",

    # Fixed seed supports experimental reproducibility
    seed=42,

    # Request more repeatable training behaviour
    deterministic=True,

    # Generate training curves and evaluation plots
    plots=True,

    # Display training progress
    verbose=True
)

print("Full YOLOv8s training completed successfully.")

CUDA available: True
Training GPU: NVIDIA GeForce RTX 4060 Laptop GPU
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolov8s_full_training, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=8, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_full_training, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117983  ultralytics.nn.modules.head.Detect           [5, 16, None, [128, 256, 512]]
Model summary: 129 layers, 11,137,535 parameters, 11,137,519 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
WARNING train: Slow image access detected (ping: 0.1±0.0 ms, read: 9.8±1.9 MB/s, size: 65.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
train: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\train\labels.cache... 3349 images, 684 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3349/3349  0.0s
WARNING val: Slow image access detected (ping: 0.1±0.0 ms, read: 9.8±1.0 MB/s, size: 66.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\valid\labels.cache... 120 images, 14 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 120/120  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and determining best 'optimizer' and 'lr0' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_full_training\labels.jpg...
Using 3349 train, 120 val images for fraction=1.0 at imgsz=640
Using 0 dataloader workers
Logging results to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_full_training
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      2.18G      1.917      3.418       1.65          5        640: 100% ━━━━━━━━━━━━ 419/419 2.4it/s 2:530.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.0it/s 2.6s0.4s
                   all        120        121      0.933      0.219      0.222      0.115

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      2.46G      1.892      1.925      1.564          8        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:370.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.0it/s 1.3s0.2s
                   all        120        121      0.973      0.191      0.251      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      2.46G      1.852      1.782      1.544          9        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:360.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.9it/s 1.3s0.2s
                   all        120        121       0.75      0.248      0.264      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      2.46G        1.8      1.648      1.508          7        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:350.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.4it/s 1.5s0.2s
                   all        120        121      0.765      0.225      0.259      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      2.46G       1.75      1.527      1.455          9        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:390.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 4.0it/s 2.0s0.3s
                   all        120        121      0.771      0.309      0.279       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      2.46G      1.726       1.48      1.444          9        640: 100% ━━━━━━━━━━━━ 419/419 3.8it/s 1:490.3sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.797      0.266      0.291      0.165

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      2.46G      1.664      1.419      1.404          7        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:350.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.9it/s 1.3s0.2s
                   all        120        121      0.844      0.229      0.294      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      2.46G      1.628      1.342      1.382          7        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:360.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.6it/s 1.4s0.2s
                   all        120        121      0.749      0.312      0.325      0.178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      2.46G      1.613      1.356      1.382         11        640: 100% ━━━━━━━━━━━━ 419/419 4.5it/s 1:340.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121      0.539      0.397      0.355      0.219

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      2.46G      1.589       1.32      1.352          8        640: 100% ━━━━━━━━━━━━ 419/419 4.4it/s 1:350.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121      0.731      0.287      0.295      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      2.46G      1.583      1.271      1.358         10        640: 100% ━━━━━━━━━━━━ 419/419 4.5it/s 1:340.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121       0.52      0.403      0.329      0.193

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      2.46G      1.516      1.203      1.326          8        640: 100% ━━━━━━━━━━━━ 419/419 4.5it/s 1:340.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.0it/s 1.3s0.2s
                   all        120        121       0.82      0.241      0.395      0.232

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      2.46G      1.511      1.181      1.321          8        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:370.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121       0.83      0.297      0.484      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      2.46G      1.496      1.163      1.312          8        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:390.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.4it/s 1.5s0.2s
                   all        120        121      0.615      0.407      0.411      0.267

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      2.46G      1.456       1.12      1.282         10        640: 100% ━━━━━━━━━━━━ 419/419 4.1it/s 1:420.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.4it/s 1.5s0.2s
                   all        120        121      0.347      0.493      0.391       0.22

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      2.46G      1.445      1.099      1.282          3        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:400.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.0it/s 1.6s0.2s
                   all        120        121      0.617      0.453      0.488      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      2.46G      1.415       1.07      1.264          7        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:410.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.6it/s 1.4s0.2s
                   all        120        121      0.422      0.468      0.463      0.269

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      2.46G      1.367      1.023      1.246         10        640: 100% ━━━━━━━━━━━━ 419/419 4.3it/s 1:380.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.9it/s 1.4s0.2s
                   all        120        121      0.784      0.399      0.484      0.277

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30      2.46G      1.338     0.9897      1.237          2        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:410.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.489      0.434      0.463      0.288

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      2.46G       1.34     0.9865      1.228         11        640: 100% ━━━━━━━━━━━━ 419/419 4.2it/s 1:390.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.325      0.428      0.398       0.24
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      2.46G      1.377     0.9655      1.263          5        640: 100% ━━━━━━━━━━━━ 419/419 5.0it/s 1:240.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        120        121      0.406       0.48      0.434      0.252

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      2.46G      1.323     0.9147      1.239          3        640: 100% ━━━━━━━━━━━━ 419/419 5.0it/s 1:230.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.772      0.354      0.451      0.259

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      2.46G      1.299     0.8813      1.226          6        640: 100% ━━━━━━━━━━━━ 419/419 5.1it/s 1:230.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121      0.479      0.559      0.528      0.297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      2.46G       1.26     0.8479      1.208          4        640: 100% ━━━━━━━━━━━━ 419/419 5.0it/s 1:250.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121      0.796      0.476      0.504      0.316

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30      2.46G      1.237     0.8316      1.183          4        640: 100% ━━━━━━━━━━━━ 419/419 5.0it/s 1:240.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121      0.525       0.57      0.473      0.269

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30      2.46G      1.222     0.8137      1.188          4        640: 100% ━━━━━━━━━━━━ 419/419 5.1it/s 1:230.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.812      0.435      0.483      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30      2.46G      1.163     0.7846      1.161          3        640: 100% ━━━━━━━━━━━━ 419/419 5.1it/s 1:230.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.7it/s 1.4s0.2s
                   all        120        121      0.413      0.585      0.473      0.266

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30      2.46G      1.143     0.7611      1.143          5        640: 100% ━━━━━━━━━━━━ 419/419 4.9it/s 1:250.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        120        121      0.472      0.556       0.46      0.322

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30      2.46G      1.101     0.7274      1.133          4        640: 100% ━━━━━━━━━━━━ 419/419 5.1it/s 1:230.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.2it/s 1.5s0.2s
                   all        120        121      0.699      0.524      0.552      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30      2.46G      1.103     0.7238      1.129          4        640: 100% ━━━━━━━━━━━━ 419/419 5.0it/s 1:240.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.0it/s 1.3s0.2s
                   all        120        121      0.751      0.525      0.559      0.326

30 epochs completed in 0.816 hours.
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_full_training\weights\last.pt, 22.5MB
Optimizer stripped from C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_full_training\weights\best.pt, 22.5MB

Validating C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\yolov8s_full_training\weights\best.pt...
Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Model summary (fused): 72 layers, 11,127,519 parameters, 0 gradients, 28.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.3s
                   all        120        121      0.753      0.525      0.559      0.326
            loose-meat          3          3      0.891      0.333      0.335      0.106

# Evaluation YOLOv8s
Assessing the best performance of the model

In [ ]:
"""
Evaluate YOLOv8s on the held-out test set
"""

#Imports
from ultralytics import YOLO
import os

# Path to the same dataset configuration used throughout both model experiments.
dataset_yaml = r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\data.yaml"

# Path to the checkpoint with the best validation performance during the full YOLOv8s training run.
best_model_s_path = os.path.join(
    "runs",
    "detect",
    "yolov8s_full_training",
    "weights",
    "best.pt"
)

# Load the best trained YOLOv8s checkpoint.
best_model_s = YOLO(best_model_s_path)

# Evaluate using exactly the same held-out test set used for YOLOv8n.
test_results_s = best_model_s.val(
    data=dataset_yaml,
    split="test",
    imgsz=640,
    batch=8,
    device=0,
    workers=0,
    plots=True
)

print("\nYOLOv8s TEST RESULTS")
print("--------------------")

print(f"Precision:      {test_results_s.box.mp:.4f}")
print(f"Recall:         {test_results_s.box.mr:.4f}")
print(f"mAP@0.5:        {test_results_s.box.map50:.4f}")
print(f"mAP@0.5:0.95:   {test_results_s.box.map:.4f}")

Ultralytics 8.4.185  Python-3.12.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Model summary (fused): 72 layers, 11,127,519 parameters, 0 gradients, 28.4 GFLOPs
WARNING val: Slow image access detected (ping: 0.1±0.0 ms, read: 10.5±0.3 MB/s, size: 65.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8\test\labels.cache... 80 images, 12 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 80/80  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.4s.2ss
                   all         80         79      0.771      0.438      0.521      0.267
            loose-meat          2          3      0.643      0.333      0.645      0.269
       packaging-error         16         23      0.598      0.583      0.534      0.167
          twisted-meat          4          4          1          0     0.0247    0.00751
              unsealed         49         49      0.843      0.837       0.88      0.623
Speed: 0.9ms preprocess, 8.4ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\VSCODE MMA3001_Project File\runs\detect\val-3

YOLOv8s TEST RESULTS
--------------------
Precision:      0.7711
Recall:         0.4383
mAP@0.5:        0.5209
mAP@0.5:0.95:   0.2668

These numbers are going to be used to compare the two models on their performance.

Next, find the performance per class of packaging defect to comapre it to the findings for the per class defects for the previous model.

In [ ]:
"""
YOLOv8s test performance per defect class
"""
#Imports
import pandas as pd

# Retrieve the test evaluation summary produced by YOLOv8s
class_results_s = test_results_s.summary()
class_results_s_df = pd.DataFrame(class_results_s)

# Display the per-class results.
class_results_s_df

,Class,Images,Instances,Box-P,Box-R,Box-F1,mAP50,mAP75,mAP50-95
0,loose-meat,2,3,0.64335,0.33333,0.43914,0.64500,0.00000,0.26917
1,packaging-error,16,23,0.59825,0.58316,0.59061,0.53397,0.01961,0.16686
2,twisted-meat,4,4,1.00000,0.00000,0.00000,0.02467,0.00355,0.00751
3,unsealed,49,49,0.84289,0.83673,0.83980,0.87992,0.73907,0.62348

It was found during the YOLOv8n model evaluation that there is no wrinkle test data ground truth hence why it doesn't show up on this table either. Therefore this is still a limitation.

# Defect Severity Analysis 
Using the new fine-tuned YOLOv8s model, we are completing an analysis on if it can identify the severity of the defect using the previously established values that can be accessed in the data exploration section of this project.

In [ ]:
"""
YOLOv8s defect-severity analysis
"""

#Imports
from ultralytics import YOLO
from pathlib import Path
import numpy as np
import pandas as pd

# Root folder containing the complete dataset
dataset_path = Path(
    r"C:\Users\sadul\OneDrive\Documents\1University\Year 3\MMA3001\Project\Pork Rasher Error-Packaging-.v4i.yolov8"
)

# Held-out test images and ground-truth annotation folders
test_images_path = dataset_path / "test" / "images"
test_labels_path = dataset_path / "test" / "labels"

# Best YOLOv8s checkpoint from the completed training run
best_model_s_path = Path(
    "runs/detect/yolov8s_full_training/weights/best.pt"
)

# Confirm that Python can find the required files
print("Test images found:", test_images_path.exists())
print("Test labels found:", test_labels_path.exists())
print("Best YOLOv8s model found:", best_model_s_path.exists())

# Class names
class_names = {
    0: "loose-meat",
    1: "packaging-error",
    2: "twisted-meat",
    3: "unsealed",
    4: "wrinkle"
}

#Re-define the functions created in the second notebook
def classify_severity(relative_area):
    """
    Classify a defect according to its normalised bounding-box area.

    Parameters
    relative_area : float
        Bounding-box area expressed as a proportion of the complete image area.

    Returns
    str
        Low, Medium or High severity.
    """

    if relative_area < 0.003254:
        return "Low"

    elif relative_area <= 0.089605:
        return "Medium"

    else:
        return "High"


def yolo_to_xyxy(x_center, y_center, width, height):
    """
    Convert a normalised YOLO bounding box from centre format to corner format.

    Parameter
        x_center, y_center, width, height

    Returns
        x_min, y_min, x_max, y_max

    """

    x_min = x_center - width / 2
    y_min = y_center - height / 2
    x_max = x_center + width / 2
    y_max = y_center + height / 2

    return np.array(
        [x_min, y_min, x_max, y_max],
        dtype=float
    )


def calculate_iou(box_a, box_b):
    """
    Calculate Intersection over Union between two boxes.

    Parameters
    box_a : array-like
        First box in x_min, y_min, x_max, y_max format.

    box_b : array-like
        Second box in x_min, y_min, x_max, y_max format.

    Returns
    float
        IoU value between 0 and 1.
    """

    # Identify the corners of the overlapping region
    intersection_x_min = max(box_a[0], box_b[0])
    intersection_y_min = max(box_a[1], box_b[1])
    intersection_x_max = min(box_a[2], box_b[2])
    intersection_y_max = min(box_a[3], box_b[3])

    # Calculate the width and height of the overlap
    intersection_width = max(
        0.0,
        intersection_x_max - intersection_x_min
    )

    intersection_height = max(
        0.0,
        intersection_y_max - intersection_y_min
    )

    # Calculate the area shared by both boxes
    intersection_area = (
        intersection_width * intersection_height
    )

    # Calculate the area of each individual box
    area_a = (
        max(0.0, box_a[2] - box_a[0])
        * max(0.0, box_a[3] - box_a[1])
    )

    area_b = (
        max(0.0, box_b[2] - box_b[0])
        * max(0.0, box_b[3] - box_b[1])
    )

    # Calculate the combined area without double-counting the overlapping region
    union_area = area_a + area_b - intersection_area

    # Prevent division by zero
    if union_area <= 0:
        return 0.0

    return intersection_area / union_area

def load_ground_truth(label_path):
    """
    Read one YOLO label file.

    Returns
    - class ID
    - normalised bounding box
    - normalised bounding-box area
    - severity classification
    """

    annotations = []

    if not label_path.exists():
        return annotations

    with open(label_path, "r") as file:

        for line in file:

            # Ignore empty lines
            if not line.strip():
                continue

            values = line.strip().split()

            class_id = int(values[0])
            x_center = float(values[1])
            y_center = float(values[2])
            width = float(values[3])
            height = float(values[4])

            # Width and height are normalised, so their product gives the relative image area
            relative_area = width * height

            annotations.append(
                {
                    "class_id": class_id,

                    "box": yolo_to_xyxy(
                        x_center,
                        y_center,
                        width,
                        height
                    ),

                    "area": relative_area,

                    "severity": classify_severity(
                        relative_area
                    )
                }
            )

    return annotations


#Load model s
severity_model_s = YOLO(str(best_model_s_path))

# The same confidence threshold used for YOLOv8n
prediction_results_s = severity_model_s.predict(
    source=str(test_images_path),
    imgsz=640,
    conf=0.25,
    device=0,
    save=False,
    stream=True,
    verbose=False
)

#Threshold to ground truth
IOU_THRESHOLD = 0.50

matched_records_s = []

total_ground_truth_s = 0
total_predictions_s = 0
unmatched_ground_truth_s = 0
unmatched_predictions_s = 0


for result in prediction_results_s:

    # Identify the image and its corresponding label file
    image_path = Path(result.path)
    label_path = test_labels_path / f"{image_path.stem}.txt"

    # Load the ground-truth objects for this image
    ground_truth = load_ground_truth(label_path)

    # Store the predictions for this image
    predictions = []

    if result.boxes is not None:

        # Predicted boxes in normalised corner format
        predicted_boxes = (
            result.boxes.xyxyn.cpu().numpy()
        )

        # Predicted class IDs
        predicted_classes = (
            result.boxes.cls.cpu().numpy().astype(int)
        )

        # Prediction confidence scores
        predicted_confidences = (
            result.boxes.conf.cpu().numpy()
        )

        for box, class_id, confidence in zip(
            predicted_boxes,
            predicted_classes,
            predicted_confidences
        ):

            # Calculate normalised predicted box dimensions
            predicted_width = max(
                0.0,
                box[2] - box[0]
            )

            predicted_height = max(
                0.0,
                box[3] - box[1]
            )

            # Calculate normalised predicted box area
            predicted_area = (
                predicted_width * predicted_height
            )

            predictions.append(
                {
                    "class_id": class_id,
                    "box": box,
                    "area": predicted_area,

                    "severity": classify_severity(
                        predicted_area
                    ),

                    "confidence": confidence
                }
            )

    total_ground_truth_s += len(ground_truth)
    total_predictions_s += len(predictions)

    # Prevent one prediction from being matched to multiple ground-truth defects
    used_prediction_indices = set()

    for gt in ground_truth:

        best_prediction_index = None
        best_iou = 0.0

        # Find the unused same-class prediction with the highest IoU value
        for prediction_index, prediction in enumerate(
            predictions
        ):

            if prediction_index in used_prediction_indices:
                continue

            # Only match defects belonging to the same class
            if prediction["class_id"] != gt["class_id"]:
                continue

            current_iou = calculate_iou(
                gt["box"],
                prediction["box"]
            )

            if current_iou > best_iou:
                best_iou = current_iou
                best_prediction_index = prediction_index

        # Accept the match when IoU is at least 0.50
        if (
            best_prediction_index is not None
            and best_iou >= IOU_THRESHOLD
        ):

            used_prediction_indices.add(
                best_prediction_index
            )

            matched_prediction = predictions[
                best_prediction_index
            ]

            matched_records_s.append(
                {
                    "image": image_path.name,

                    "class_id": gt["class_id"],

                    "class_name": class_names[
                        gt["class_id"]
                    ],

                    "iou": best_iou,

                    "confidence": matched_prediction[
                        "confidence"
                    ],

                    "ground_truth_area": gt["area"],

                    "predicted_area": matched_prediction[
                        "area"
                    ],

                    "ground_truth_severity": gt[
                        "severity"
                    ],

                    "predicted_severity": matched_prediction[
                        "severity"
                    ],

                    "severity_correct": (
                        gt["severity"]
                        == matched_prediction["severity"]
                    )
                }
            )

        else:
            # Ground-truth defect was missed, misclassified or insufficiently localised
            unmatched_ground_truth_s += 1

    # Predictions that were not assigned to a ground-truth defect are counted as unmatched predictions
    unmatched_predictions_s += (
        len(predictions) - len(used_prediction_indices)
    )

#Create table of results
severity_results_s_df = pd.DataFrame(
    matched_records_s
)

print("YOLOv8s SEVERITY VALIDATION COMPLETE")
print("------------------------------------")

print(
    f"Ground-truth defects:       "
    f"{total_ground_truth_s}"
)

print(
    f"Model predictions:          "
    f"{total_predictions_s}"
)

print(
    f"Matched defects:            "
    f"{len(severity_results_s_df)}"
)

print(
    f"Unmatched ground truth:     "
    f"{unmatched_ground_truth_s}"
)

print(
    f"Unmatched predictions:      "
    f"{unmatched_predictions_s}"
)

if len(severity_results_s_df) > 0:

    # Severity accuracy among correctly matched defects
    severity_accuracy_s = (
        severity_results_s_df[
            "severity_correct"
        ].mean()
    )

    # Mean absolute error between predicted and ground-truth normalised box areas
    area_mae_s = np.mean(
        np.abs(
            severity_results_s_df["predicted_area"]
            - severity_results_s_df[
                "ground_truth_area"
            ]
        )
    )

    # Proportion of all ground-truth defects that were successfully detected and matched
    matched_detection_rate_s = (
        len(severity_results_s_df)
        / total_ground_truth_s
    )

    # Number of ground-truth defects that were detected and given the correct severity category
    correctly_assessed_s = int(
        severity_results_s_df[
            "severity_correct"
        ].sum()
    )

    # End-to-end performance treats missed detections as unsuccessful severity assessments
    end_to_end_severity_rate_s = (
        correctly_assessed_s
        / total_ground_truth_s
    )

    print("\nYOLOv8s SEVERITY RESULTS")
    print("------------------------")

    print(
        f"Matched severity accuracy: "
        f"{severity_accuracy_s:.4f}"
    )

    print(
        f"Matched detection rate:     "
        f"{matched_detection_rate_s:.4f}"
    )

    print(
        f"End-to-end severity rate:    "
        f"{end_to_end_severity_rate_s:.4f}"
    )

    print(
        f"Bounding-box area MAE:       "
        f"{area_mae_s:.6f}"
    )

else:
    print(
        "No defects satisfied the matching criteria."
    )


# Display the first ten successfully matched defects
severity_results_s_df.head(10)

Test images found: True
Test labels found: True
Best YOLOv8s model found: True
YOLOv8s SEVERITY VALIDATION COMPLETE
------------------------------------
Ground-truth defects:       79
Model predictions:          84
Matched defects:            57
Unmatched ground truth:     22
Unmatched predictions:      27

YOLOv8s SEVERITY RESULTS
------------------------
Matched severity accuracy: 0.9649
Matched detection rate:     0.7215
End-to-end severity rate:    0.6962
Bounding-box area MAE:       0.010055

,image,class_id,class_name,iou,confidence,ground_truth_area,predicted_area,ground_truth_severity,predicted_severity,severity_correct
0,frame_with_red_102_jpg.rf.10163b7e614de52a86d7...,3,unsealed,0.750305,0.770835,0.123912,0.164568,High,High,True
1,frame_with_red_1271_jpg.rf.fe7e60f579e43de1fb7...,3,unsealed,0.793230,0.865260,0.096543,0.103160,High,High,True
2,frame_with_red_1298_jpg.rf.bbe700517e6a8b83719...,1,packaging-error,0.703775,0.561287,0.053331,0.037533,Medium,Medium,True
3,frame_with_red_1405_jpg.rf.061b0a529d86947d726...,3,unsealed,0.833281,0.866289,0.100823,0.102253,High,High,True
4,frame_with_red_1427_jpg.rf.adb68bb9baac518a460...,3,unsealed,0.760166,0.722500,0.088035,0.095656,Medium,High,False
5,frame_with_red_1458_jpg.rf.ae22a9f677e9aed6399...,1,packaging-error,0.712518,0.705208,0.078652,0.062714,Medium,Medium,True
6,frame_with_red_1521_jpg.rf.8c2f93027627984923b...,3,unsealed,0.864926,0.909327,0.131944,0.152331,High,High,True
7,frame_with_red_161_jpg.rf.f72001c0662bd4c49556...,3,unsealed,0.847169,0.533342,0.041968,0.048567,Medium,Medium,True
8,frame_with_red_1695_jpg.rf.0fcc67310f01b5c3361...,0,loose-meat,0.685915,0.888553,0.013494,0.009423,Medium,Medium,True
9,frame_with_red_1787_jpg.rf.2ea27acbeb8b9e0111c...,3,unsealed,0.866026,0.873718,0.121682,0.118910,High,High,True

### YOLOv8s Severity Validation Results

YOLOv8s successfully matched 57 of the 79 ground-truth defects, corresponding to a matched detection rate of 72.15%. This was slightly higher than the 70.89% matched detection rate achieved by YOLOv8n.

Among the matched defects, YOLOv8s correctly classified 55 of 57 severity categories, producing a matched severity accuracy of 96.49%. When missed defects were treated as unsuccessful severity assessments, the end-to-end severity-assessment rate was only 69.62%.

However, YOLOv8s produced 27 unmatched predictions compared with 20 for YOLOv8n. This supports the detection results showing that YOLOv8s achieved greater recall but lower precision. Therefore, YOLOv8s identified a greater proportion of defects but also produced more unmatched detections.

# Confusion matrix

In [ ]:
"""
Create a confusion matrix 
"""

#Imports
import pandas as pd

#Order
severity_order = ["Low", "Medium", "High"]

# Create a confusion matrix comparing the ground-truth severity category against the severity predicted by YOLOv8s.
severity_confusion_matrix_s = pd.crosstab(
    severity_results_s_df["ground_truth_severity"],
    severity_results_s_df["predicted_severity"],
    rownames=["Ground Truth"],
    colnames=["Predicted"],
    dropna=False
)

severity_confusion_matrix_s = severity_confusion_matrix_s.reindex(
    index=severity_order,
    columns=severity_order,
    fill_value=0
)

# Display the completed confusion matrix.
severity_confusion_matrix_s

Predicted     Low  Medium  High
Ground Truth
Low             0       0     0
Medium          0      24     2
High            0       0    31

YOLOv8s correctly classified the severity of 55 of the 57 successfully matched defects, corresponding to a matched severity accuracy of 96.49%.

Of the 26 Medium-severity defects, 24 were correctly classified while two were overestimated as High severity. All 31 matched High-severity defects were correctly classified.

No Low-severity defects were present among the successfully matched test detections. Therefore, the performance of YOLOv8s for Low-severity defect assessment cannot be independently evaluated using the available test sample.

Compared with YOLOv8n, YOLOv8s demonstrated slightly improved severity classification performance, particularly for High-severity defects.